name: command
on: issue_comment

jobs:
  env-setup:
    name: env setup
    if: ${{ github.event.issue.pull_request }} && startsWith(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    outputs:
      workbench_version: ${{ steps.get_workbench_version_info.outputs.workbench_version }}
      workbench_fed_version: ${{ steps.get_workbench_version_info.outputs.workbench_fed_version }}
    steps:
      - name: get workbench version info
        id: get_workbench_version_info
        run: |
          read -r _ workbench_version workbench_fed_version <<< "${COMMENT#/test }"
          echo "workbench_version=$workbench_version" >> $GITHUB_OUTPUT
          echo "workbench_fed_version=$workbench_fed_version" >> $GITHUB_OUTPUT
        env:
          COMMENT: ${{ github.event.comment.body }}
  pr_commented:
    # This job only runs for pull request comments
    needs: [ env-setup ]
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    env:
      WORKBENCH_VERSION: ${{ needs.env-setup.outputs.workbench_version }}
      WORKBENCH_FED_VERSION: ${{ needs.env-setup.outputs.workbench_fed_version }}
    steps:
      - name: report
        if: contains(github.event.comment.body, '/test')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! will run ${{env.WORKBENCH_VERSION}} and fed: ${{env.WORKBENCH_FED_VERSION}}'
            })
# on:
#   # pull_request:
#   issue_comment:
# jobs:
#   pr_commented:
#     # if: ${{ github.event.issue.pull_request }}
#     runs-on: [ubuntu-latest]
#     steps:
#       - name: debug
#         run: |
#           echo hello world
#         env:
#           EVENT: ${{ github.event.issue }}
#       - name: say hello
#         if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
#         run: |
#           echo say hello
