name: pr
run-name: ${{ github.event_name=='workflow_dispatch' && format('Manually build feature branch {0}', github.event.inputs.pull_request_id) || '' }}
on:
  pull_request_review:
    types: [submitted]
  pull_request:
  workflow_dispatch:
    inputs:
      pull_request_id:
        description: The pull request id that you want to test
        type: string

jobs:
  pr_commented:
    # This job only runs for pull request comments
    # if: >-
    #   github.event.inputs.pull_request_id ||
    #   github.event.number
    if: >- 
      startsWith(github.head_ref, 'p/') ||
      github.event.review.state == 'APPROVED' ||
      github.event_name=='workflow_dispatch'
    name: PR comment
    runs-on: ubuntu-latest
    env:
      TEXT: ${{ github.event.inputs.pull_request_id || format('Hello {0}', github.event.number) || 'default'}}-test
      PR:  ${{ github.event.inputs.pull_request_id || github.event.number}}
      group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
      DE: ${{ toJson(github)}}
      REF: ${{ github.ref}}
    steps:
      - name: debug
        run: |
          echo "env: ${EVENT}, pr: ${PRN}"
          echo "TXT: ${TEXT}"
          echo "PR: ${PR}"
          echo "group: ${group}"
          echo "DE: ${DE}"
          echo "REF: ${REF}"
        env:
          EVENT: ${{ github.event.inputs.pull_request_id }}
          PRN: ${{github.event.number}}
      - name: report
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{env.PR}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! will run ${{env.TEXT}}'
            })
  beh:
    needs: [ pr_commented ]
    runs-on: [ubuntu-latest]
    steps:
      - name: say hello
        run: |
          echo say hello

# on:
#   # pull_request:
#   issue_comment:
# jobs:
#   pr_commented:
#     # if: ${{ github.event.issue.pull_request }}
#     runs-on: [ubuntu-latest]
#     steps:
#       - name: debug
#         run: |
#           echo hello world
#         env:
#           EVENT: ${{ github.event.issue }}
#       - name: say hello
#         if: contains(github.event.comment.body, '/support1')   # check the comment if it contains the keywords
#         run: |
#           echo say hello
